spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mariadb://localhost:3306/petclinic
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      schema-locations: classpath*:db/mysql/schema.sql
      data-locations: classpath*:db/mysql/data.sql
      init: ALWAYS
