# application.yml
server:
  port: 0
  shutdown: graceful

spring:
  sql:
    init:
      schema-locations: classpath*:db/hsqldb/schema.sql
      data-locations: classpath*:db/hsqldb/data.sql
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    config:
      allow-override: true
      override-none: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1
---
# chaos-monkey.yml
spring:
  config:
    activate:
      on-profile: chaos-monkey

management:
  endpoint:
    chaosmonkey:
      enabled: true

chaos:
  monkey:
    enabled: true
    watcher:
      component: false
      controller: false
      repository: false
      rest-controller: false
      service: false

---
# mysql.yml
spring:
  config:
    activate:
      on-profile: mysql

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mysql-db:3306/questiondb
