# question.yml
questions:
  cache:
    ttl: 60
    heap-size: 100

spring:
  profiles:
    include:
      - default
      - docker

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

server:
  port: 8083

config:
  activate:
    on-profile: docker

zipkin:
  baseUrl: http://tracing-server:9411

