questions:
  cache:
    ttl: 60
    heap-size: 100

---
spring:
  config:
    activate:
      on-profile: default
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}

---
spring:
  config:
    activate:
      on-profile: docker
  zipkin:
    baseUrl: http://tracing-server:9411
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/



---
spring:
  datasource:
    url: jdbc:mysql://mysql-db:3306/questiondb
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
